apiVersion: v1
kind: Service
metadata:
  name: plattr-operator-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: plattr-operator
spec:
  selector:
    app.kubernetes.io/name: plattr-operator
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: metrics
