apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: previewenvironments.platform.internal
spec:
  group: platform.internal
  names:
    kind: PreviewEnvironment
    listKind: PreviewEnvironmentList
    plural: previewenvironments
    singular: previewenvironment
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: App
          type: string
          jsonPath: .spec.applicationRef
        - name: PR
          type: integer
          jsonPath: .spec.pullRequest
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: URL
          type: string
          jsonPath: .status.url
        - name: Expires
          type: string
          jsonPath: .status.expiresAt
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - applicationRef
                - pullRequest
                - branch
              properties:
                applicationRef:
                  type: string
                  description: Name of the parent Application
                pullRequest:
                  type: integer
                  description: PR number
                branch:
                  type: string
                  description: Git branch name
                ttl:
                  type: string
                  default: "72h"
                  description: Time to live before auto-cleanup
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Provisioning
                    - Running
                    - Failed
                    - Terminating
                url:
                  type: string
                expiresAt:
                  type: string
                  format: date-time
